import { type ApiRequest, type ApiResponse } from "../_types.js";
import { type HandoffSession, saveTelegramMessage } from "./storage.js";
export const MAX_QUESTION_LENGTH = 2000, MAX_MESSAGE_LENGTH = 2000;
export type ConversationItem = { role: "user" | "assistant"; content: string };
export function methodNotAllowed(response: ApiResponse, allowed: string[]) { response.status(405).json({ ok: false, error: "method_not_allowed", allowed }); }
export function bodyObject(request: ApiRequest) { if (typeof request.body === "string") { try { return JSON.parse(request.body) as Record<string, unknown>; } catch { return null; } } return request.body && typeof request.body === "object" ? request.body as Record<string, unknown> : null; }
export const validSessionId = (value: unknown): value is string => typeof value === "string" && /^[A-Za-z0-9_-]{8,128}$/.test(value);
export const escapeTelegramHtml = (value: string) => value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
export const headerValue = (request: ApiRequest, name: string) => { const value = request.headers[name.toLowerCase()]; return Array.isArray(value) ? value[0] : value; };
export function telegramConfig() { const token = process.env.TELEGRAM_BOT_TOKEN, chatId = process.env.TELEGRAM_CHAT_ID, webhookSecret = process.env.TELEGRAM_WEBHOOK_SECRET; if (!token || !chatId || !webhookSecret) throw new Error("telegram_not_configured"); return { token, chatId, webhookSecret }; }
export async function telegramRequest(token: string, method: string, body: unknown) { const response = await fetch(`https://api.telegram.org/bot${token}/${method}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json() as { ok?: boolean; result?: { message_id?: number } }; if (!response.ok || !result.ok) throw new Error("telegram_request_failed"); return result; }
export async function sendHandoff(session: HandoffSession) { const { token, chatId } = telegramConfig(); const text = ["🟢 <b>New Inji Conversation</b>", `<b>Visitor:</b> ${escapeTelegramHtml(session.visitorName)}`, `<b>Company:</b> ${escapeTelegramHtml(session.company || "Not provided")}`, `<b>Email:</b> ${escapeTelegramHtml(session.email || "Not provided")}`, `<b>Phone:</b> ${escapeTelegramHtml(session.phone || "Not provided")}`, "", "<b>Question:</b>", escapeTelegramHtml(session.question), "", `<b>Session:</b> <code>${escapeTelegramHtml(session.sessionId)}</code>`, "", "Reply directly to this message to chat with the visitor."].join("\n"); const result = await telegramRequest(token, "sendMessage", { chat_id: chatId, text, parse_mode: "HTML", reply_markup: { inline_keyboard: [[{ text: "Take Chat", callback_data: "take" }, { text: "Typing…", callback_data: "typing_on" }], [{ text: "Stop Typing", callback_data: "typing_off" }, { text: "Close Chat", callback_data: "close" }]] } }); if (!result.result?.message_id) throw new Error("telegram_message_missing"); await saveTelegramMessage(session.sessionId, result.result.message_id); }
