import { useEffect, useRef, useState } from "react";
import { Bot, Send, Sparkles, X } from "lucide-react";
import { createPortal } from "react-dom";
import { getInjiResponse } from "./injiKnowledge";

type Message = { id: string; role: "user" | "assistant" | "human"; text: string; timestamp: number; agentName?: string };
type Status = "idle" | "lead_form" | "transferring" | "waiting" | "active" | "closed" | "expired";
const welcomeKey = "formiva_inji_welcome_seen", sessionKey = "formiva_inji_session_id", handoffKey = "formiva_inji_pending_handoff";
const suggestions = ["What is Formiva?", "How does CaseFlow work?", "How does AI work?", "Employee onboarding", "Features", "Pricing", "Talk to the team"];
const id = (prefix = "local") => `${prefix}-${globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random().toString(36).slice(2)}`}`;

export default function InjiAI() {
  const [open, setOpen] = useState(false), [welcome, setWelcome] = useState(false), [input, setInput] = useState(""), [responding, setResponding] = useState(false);
  const [status, setStatus] = useState<Status>("idle"), [handoffQuestion, setHandoffQuestion] = useState(""), [agentName, setAgentName] = useState(""), [typing, setTyping] = useState(false);
  const [lead, setLead] = useState({ name: "", company: "", phone: "", email: "" }), [leadError, setLeadError] = useState("");
  const [feedback, setFeedback] = useState({ rating: 0, text: "", submitting: false, submitted: false, error: "" });
  const [messages, setMessages] = useState<Message[]>([{ id: "welcome", role: "assistant", text: "Hi! I'm Inji. How can I help you learn about Formiva?", timestamp: 0 }]);
  const session = useRef(""), timer = useRef<number | null>(null), end = useRef<HTMLDivElement>(null);
  const add = (role: Message["role"], text: string) => setMessages(current => [...current, { id: id(), role, text, timestamp: Date.now() }]);
  useEffect(() => { try { setWelcome(localStorage.getItem(welcomeKey) !== "true"); session.current = localStorage.getItem(sessionKey) || id("session"); localStorage.setItem(sessionKey, session.current); if (localStorage.getItem(handoffKey) === session.current) setStatus("waiting"); } catch { session.current = id("session"); setWelcome(true); } return () => { if (timer.current) clearTimeout(timer.current); }; }, []);
  useEffect(() => { end.current?.scrollIntoView({ behavior: "smooth", block: "nearest" }); }, [messages, status, typing, responding]);
  useEffect(() => {
    if (!open || !["waiting", "active", "closed"].includes(status)) return;
    let cancelled = false;
    const poll = async () => { try { const response = await fetch(`/api/inji/reply?sessionId=${encodeURIComponent(session.current)}`); if (!response.ok || cancelled) return; const data = await response.json() as { status?: Status; messages?: Message[]; agentName?: string; isTyping?: boolean; feedbackSubmitted?: boolean }; if (!data.status || cancelled) return; if (["active", "closed", "expired"].includes(data.status)) setStatus(data.status); if (data.agentName) setAgentName(data.agentName); setTyping(Boolean(data.isTyping) && data.status === "active"); if (data.feedbackSubmitted) setFeedback(current => ({ ...current, submitted: true })); const remoteMessages = data.messages; if (remoteMessages) setMessages(current => { const merged = new Map(current.map(m => [m.id, m])); remoteMessages.forEach(m => merged.set(m.id, { ...m, agentName: data.agentName || m.agentName })); return Array.from(merged.values()).sort((a, b) => a.timestamp - b.timestamp); }); } catch { /* next poll retries */ } };
    void poll(); const interval = window.setInterval(() => void poll(), 2500); return () => { cancelled = true; clearInterval(interval); };
  }, [open, status]);
  const seen = () => { setWelcome(false); try { localStorage.setItem(welcomeKey, "true"); } catch { /* no storage */ } };
  function beginHandoff(question: string) { setHandoffQuestion(question); setStatus("lead_form"); add("assistant", "Let's connect you with the Formiva Team\n\nI can connect you with a member of our team. Just a few details first."); }
  async function submitLead(event: React.FormEvent) { event.preventDefault(); const name = lead.name.trim(), email = lead.email.trim(), phone = lead.phone.trim(); if (!name) return setLeadError("Please enter your name."); if (!phone && !email) return setLeadError("Add a contact number or business email."); if (email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) return setLeadError("Enter a valid business email."); if (phone && !/^[+()\-\s\d]{7,25}$/.test(phone)) return setLeadError("Enter a valid contact number."); setLeadError(""); setStatus("transferring"); try { const response = await fetch("/api/inji/handoff", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ sessionId: session.current, question: handoffQuestion, details: { name, company: lead.company.trim(), email, phone }, conversation: messages.map(m => ({ role: m.role === "human" ? "assistant" : m.role, content: m.text })) }) }); if (!response.ok) throw new Error(); try { localStorage.setItem(handoffKey, session.current); } catch { /* no storage */ } add("assistant", "Transferring you to a member of the Formiva Team…"); setStatus("waiting"); } catch { setStatus("lead_form"); setLeadError("We couldn't connect you right now. Please try again."); } }
  async function submitFeedback() { if (!feedback.rating || feedback.submitting) return; setFeedback(current => ({ ...current, submitting: true, error: "" })); try { const response = await fetch("/api/inji/feedback", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ sessionId: session.current, rating: feedback.rating, feedback: feedback.text }) }); if (!response.ok) throw new Error(); setFeedback(current => ({ ...current, submitting: false, submitted: true })); } catch { setFeedback(current => ({ ...current, submitting: false, error: "We couldn't submit your feedback. Please try again." })); } }
  function send(question = input) { const text = question.trim(); if (!text || responding || ["lead_form", "transferring", "waiting", "closed"].includes(status)) return; setInput(""); if (status === "active") { const messageId = id("visitor"); setMessages(current => [...current, { id: messageId, role: "user", text, timestamp: Date.now() }]); void fetch("/api/inji/message", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ sessionId: session.current, message: text, messageId }) }); return; } add("user", text); setResponding(true); timer.current = window.setTimeout(() => { const answer = getInjiResponse(text); add("assistant", answer.answer); if (answer.id === "fallback") beginHandoff(text); setResponding(false); timer.current = null; }, 650); }
  const disabled = responding || ["lead_form", "transferring", "waiting", "closed"].includes(status);
  return createPortal(<>
    {welcome && !open && <aside className="inji-welcome-teaser" aria-label="Inji welcome"><button type="button" className="inji-teaser-copy" onClick={() => { seen(); setOpen(true); }}><span>Hi! I'm Inji</span><strong>Need help exploring Formiva?</strong></button><button type="button" className="inji-teaser-action" onClick={() => { seen(); setOpen(true); }}>Ask Inji</button><button type="button" className="inji-teaser-dismiss" onClick={seen} aria-label="Dismiss Inji welcome">×</button></aside>}
    {open && <section className="inji-chat" aria-label="Inji chat assistant"><div className="inji-header"><div className="inji-title"><div className="inji-avatar"><Bot size={18}/><Sparkles className="inji-avatar-spark" size={11}/></div><div><strong>Inji</strong><span>Formiva's AI assistant</span></div></div><button className="inji-close" onClick={() => setOpen(false)} aria-label="Close Inji" type="button"><X size={19}/></button></div><div className="inji-messages" aria-live="polite">
      {messages.map((message, index) => <div key={message.id} className={`inji-message ${message.role === "user" ? "inji-user" : "inji-bot"} ${index === 0 ? "inji-welcome" : ""}`}>{message.role === "human" && <><strong>Formiva Team · {message.agentName || agentName || "Team"}</strong><br/></>}{message.text}</div>)}
      {status === "lead_form" && <form className="inji-lead-form" onSubmit={submitLead}><strong>Let's connect you with the Formiva Team</strong><p>I can connect you with a member of our team. Just a few details first.</p><label>Your name *<input value={lead.name} onChange={e => setLead({ ...lead, name: e.target.value })} autoComplete="name"/></label><label>Company name<input value={lead.company} onChange={e => setLead({ ...lead, company: e.target.value })} autoComplete="organization"/></label><label>Contact number<input value={lead.phone} onChange={e => setLead({ ...lead, phone: e.target.value })} inputMode="tel" autoComplete="tel"/></label><label>Business email<input value={lead.email} onChange={e => setLead({ ...lead, email: e.target.value })} type="email" autoComplete="email"/></label><small>Your details will be shared with the Formiva Team for this conversation.</small>{leadError && <p className="inji-form-error" role="alert">{leadError}</p>}<button type="submit">Connect me with the team</button></form>}
      {status === "waiting" && <div className="inji-handoff-status" role="status">Your question and details have been sent to the team. I'll show their response here.<br/><b>Waiting for Formiva Team…</b></div>}{status === "active" && <div className="inji-handoff-status">Connected with {agentName || "the Formiva Team"}</div>}{typing && <div className="inji-agent-typing" role="status">{agentName || "Formiva Team"} is typing…</div>}
      {status === "closed" && <><div className="inji-handoff-status">Your conversation with the Formiva Team has ended.</div>{feedback.submitted ? <div className="inji-handoff-status">Thanks for your feedback!</div> : <div className="inji-feedback-form"><strong>Thanks for chatting with the Formiva Team!</strong><p>How was your experience?</p><div className="inji-rating" aria-label="Rating">{[1,2,3,4,5].map(r => <button type="button" key={r} aria-pressed={feedback.rating === r} className={feedback.rating === r ? "active" : ""} onClick={() => setFeedback(current => ({ ...current, rating: r }))}>{r}</button>)}</div><label>Tell us how we did (optional)<textarea maxLength={1000} value={feedback.text} onChange={e => setFeedback(current => ({ ...current, text: e.target.value }))}/></label>{feedback.error && <p className="inji-form-error" role="alert">{feedback.error}</p>}<button type="button" disabled={!feedback.rating || feedback.submitting} onClick={() => void submitFeedback()}>{feedback.submitting ? "Submitting…" : "Submit feedback"}</button></div>}</>}
      {responding && <div className="inji-message inji-bot inji-typing" role="status"><span>Inji</span><span className="inji-typing-dots" aria-hidden="true"><i/><i/><i/></span></div>}{messages.length === 1 && <div className="inji-suggestions" aria-label="Suggested questions"><span>Try asking</span>{suggestions.map(q => <button key={q} type="button" onClick={() => send(q)} disabled={responding}>{q}</button>)}</div>}<div ref={end}/></div><form className="inji-input" onSubmit={e => { e.preventDefault(); send(); }}><input value={input} onChange={e => setInput(e.target.value)} placeholder={status === "active" ? "Message the Formiva Team…" : "Ask Inji…"} aria-label="Chat message" disabled={disabled}/><button type="submit" aria-label="Send message" disabled={disabled}><Send size={17}/></button></form></section>}
    <button className={`inji-button ${open ? "inji-button-open" : ""}`} onClick={() => open ? setOpen(false) : (seen(), setOpen(true))} aria-label={open ? "Close Inji" : "Ask Inji"} type="button">{open ? <X size={22}/> : <Bot size={22}/>} {!open && <span>Ask Inji</span>}</button>
  </>, document.body);
}
